[package]
name = "llama-rs"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.13.1"
half = "2.2.1"
ggml-raw = { path = "../ggml-raw" }
partial_sort = "0.2.0"
thiserror = "1.0"

rand = { workspace = true }
serde = { version = "1.0.156", features = ["derive"] }
bincode = "1.3.3"
